PORT: 9000
RABBIT_HOST: localhost
RABBIT_PORT: 5672
RABBIT_USER: rabbitmq
RABBIT_PASSWORD: rabbitmq
POSTGRES_USERNAME: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_URL: jdbc:postgresql://127.0.0.1:5432/kinjo-dev
REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD:
REDIS_USER: default
REDIS_DB: 1
PRESENCE_PULLER_ENABLED: false
REGIONS: US_EAST_1, US_EAST_4, US_EAST_5, US_SOUTH_1, US_WEST_1, US_WEST_3
PULLER_MESSAGE_SIZE: 500
FRIENDS_LIST_CRON: 0 * * * * *